server:
  port: 8082

post:
  scheme: http
  host: localhost
  port: 8080
  path: /api/v1/post
  baseUrl: http://localhost:8080/api/v1/post

review:
  scheme: http
  host: localhost
  port: 8081
  path: /api/v1/post_comment
  baseUrl: http://localhost:8081/api/v1/post_comment